### ISSUE TITLE
[RMP] Deep Ranking Models (TF)

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#110]
# Models ( Data Scientist )
[[RMP] Ranking - TF : Wide and Deep, DLRM, DeepFM](https://github.com/NVIDIA-Merlin/models/issues/48)

- [x] https://github.com/NVIDIA-Merlin/models/issues/235
- [ ] https://github.com/NVIDIA-Merlin/models/issues/154
- [ ] YouTube DNN
     - https://github.com/NVIDIA-Merlin/models/issues/204
     Note: YoutubeDNN is both a ranking and retrieval model
- [ ] Note: Check with Product and Eng. if youtube DNN (ranking) will be covered in a later release after 22.04 or totally removed from scope
- [x] DLRM
- [x] DCN
    - https://github.com/NVIDIA-Merlin/models/pull/187

# NVTabular (Data scientist / Product Engineer) 
N/A? 
- [x] check if there are any gaps for NVTabular  ( End to End example validates no gaps. Tracked below )

# Systems (Data scientist / Product Engineer)
- [x] Triton operators for serving ranking models
     - https://github.com/NVIDIA-Merlin/NVTabular/pull/1391

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-823

**Comment by viswa-nvidia** [comment]
@sararb update the tickets for youtube dnn retrieval and ranking to this ticket

**Comment by viswa-nvidia** [comment]
@sararb ,please link your research frame work tickets and mark them. Thanks

**Comment by sararb** [comment]
- Youtube-DNN is a two-stage recommender model with two architectures for retrieval and ranking steps. 
- This closed [PR](https://github.com/NVIDIA-Merlin/models/pull/152) implemented the retrieval architecture in merlin-models. 
- The ranking architecture is not implemented yet, and I have just linked this ticket to the corresponding issue.

**Comment by karlhigley** [comment]
YouTube DNN and Wide & Deep have moved to separate issues:

- https://github.com/NVIDIA-Merlin/Merlin/issues/278
- https://github.com/NVIDIA-Merlin/Merlin/issues/279
