### ISSUE TITLE
[RMP] Documentation for 1.0

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#111]
# Merlin:
- [x] NVIDIA-Merlin/Merlin#145
- [x] NVIDIA-Merlin/Merlin#130
- [x] https://github.com/NVIDIA-Merlin/Merlin/pull/174

# Core:
- [x] Set up automated docs builds

# Models:
- [x] NVIDIA-Merlin/models#285
- [x]  Set up automated doc builds
  - [x] https://github.com/NVIDIA-Merlin/models/pull/229
  - [x] https://github.com/NVIDIA-Merlin/models/pull/174)

# NVTabular:
- [ ] README revisions?
Note: There are some un related items in the readme such as container build process for other repos. Should this be cleaned ? There is documentaiton regarding examples for other repos. Should this be moved ? 

# Systems:

- [x] https://github.com/NVIDIA-Merlin/systems/issues/4
- [x] Set up automated docs builds

# Transformers4Rec:

- [x] Set up automated doc builds
  - [x]  https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/382

# HugeCTR
- [x] Convert HCTR doc to sphinx keeping SOK as separate doc
- <s>Note: Michael was able to resolve the issue. Will have SOK and HCTR under one Sphinx doc. Will have it for 22.04</s>
- [x] Make all our repos to have same headline (repo name) | (doc link)
- Note: Will have it for 22.04
- [ ] Centralized doc will follow next release 
- Will target 22.05
Individual repo doc updates 
Expecting inputs from engineering team. Michael to share updates on how it affects his other works 

# Support matrix
- [x] Create One Support Matrix for Merlin
  - [x] https://github.com/NVIDIA-Merlin/Merlin/pull/174
  - [ ] #177
  - [x] Change the title to  ‘Merlin Support Matrix’
  - [x] Update for all 6 containers
  - [x] Place newer information first
  - [x] Table per container 
  - [ ] Page for each year is nice-to-have
  
- [ ]Support matrix - Combining tables to Training and Inference instead of 6  ( after 22.04)
  - [ ] Michael to draft POC and will review

Aha! Link: https://nvaiinfa.aha.io/features/MERLIN-822

**Comment by mikemckiernan** [comment]
PR https://github.com/NVIDIA-Merlin/models/pull/193 is meant to encompass https://github.com/NVIDIA-Merlin/models/issues/192

**Comment by karlhigley** [comment]
I've added some check boxes for other docs related work I think is in scope (some of which I'm on the hook for, and some of which we'll want to figure out how to handle.)

**Comment by viswa-nvidia** [comment]
@EvenOldridge  @benfred , do we need to revise the readme for NVTabular ?

**Comment by viswa-nvidia** [comment]
@EvenOldridge , @benfred @karlhigley @mikemckiernan - in NVTabular readme - There are some un related items in the readme such as container build process for other repos. Should this be cleaned ? There is documentaiton regarding examples for other repos. Should this be moved ?

**Comment by karlhigley** [comment]
Sounds like the HugeCTR work here is done, if I understood correctly from @mikemckiernan?

**Comment by EvenOldridge** [comment]
1.0 release is complete.  Let's create a new docs ticket.
