### ISSUE TITLE
[RMP] Rework the older Merlin example notebooks to use other Merlin libraries

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#253]
# NVTabular

_**Note**: The scope of this is TBD and to be discussed in upcoming meetings_

Currently, nvtabular holds all integration tests. These tests are supposed to evaluate integration of NVTabular with the merlin components and target frameworks (i.e. Tensorflow, Torch). Updates need to be made to meet this requirement.

- [x] Integrate Merlin Models into the example notebooks
- [x] Integrate Merlin Systems into the example notebooks
- [x] Migrate the NVT example notebook unit tests to use [Testbook](https://github.com/nteract/testbook)
This PR closes all three above 
- [x] https://github.com/NVIDIA-Merlin/Merlin/pull/779

- [x] Set up integration tests for NVT example notebooks
## move to a separate ticket 
- [x] NVIDIA-Merlin/NVTabular#1416
- [ ] Decide what metrics to capture to ASV for NVTabular notebooks
- [ ] NVIDIA-Merlin/NVTabular#1417
- [ ] #797

**Comment by karlhigley** [comment]
Excerpted from #205, which is specifically focused on improving testing

**Comment by jperez999** [comment]
we should also decide what to migrate to other repos and what to remove all together.

**Comment by karlhigley** [comment]
Another related issue (potentially as follow-up work to this) is that we'd like to remove the dataloaders and framework utils from NVTabular since they've moved to Merlin Models, but the current example notebooks rely heavily on both the NVT dataloaders and framework utils. (So does the `bench` directory, for that matter.)

**Comment by bschifferer** [comment]
thanks for splitting. I think we need one first ToDo - "Decide where current NVTabular examples will stay" & "Decide which NVTabular examples should be migrated to Merlin Models & Merlin Systems"

**Comment by karlhigley** [comment]
Sounds good to me! Go ahead and edit the list to make it reflect how you'd like to tackle the work?

(I'm just the scribe here, trying to make sure we have things written down. I have no strong opinions about how this should go.)

**Comment by EvenOldridge** [comment]
@bschifferer can you give an update on this ticket?

**Comment by EvenOldridge** [comment]
@bschifferer can you follow up.

**Comment by viswa-nvidia** [comment]
@bschifferer please update this ticket definition
