### ISSUE TITLE
[RMP] Improve the speed of training retrieval models with Merlin Models

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#259]
## Problem:
Merlin models needs to differentiate itself relative to other RecSys library solutions.  One of those areas of differentiation needs to be performance on the GPU.  If our libraries don't follow best practices and achieve fast performance that we can measure on GPU then our potential customers have no reason to use the library. 

## Goal: 
- Provide performant retrieval models in production
- Follow best practices by our colleagues for GPU optimization

## Constraints
- Merlin models is built on top of Tensorflow

### Retrieval models

- [x] https://github.com/NVIDIA-Merlin/models/issues/339 
- [x] https://github.com/NVIDIA-Merlin/models/issues/338
- [x] https://github.com/NVIDIA-Merlin/models/issues/336

**Comment by EvenOldridge** [comment]
@gabrielspmoreira @marcromeyn Where are we at with the perf regressions we were seeing?  Can we close this?

**Comment by viswa-nvidia** [comment]
Check this bug is done https://github.com/NVIDIA-Merlin/models/issues/339 and this issue should be closed. This is an ongoing effort. The profiling portion will be spun off as a separate RMP ticket

**Comment by gabrielspmoreira** [comment]
@EvenOldridge @viswa-nvidia  As we discussed in the Grooming meeting today, I have tested the pending runtime issue of retrieval models training (https://github.com/NVIDIA-Merlin/models/issues/339) with the current implementation (for both V1 and V2) and it doesn't occur anymore. So that bug was closed.
I also extracted the profiling tasks of retrieval model pipelines to a new RMP #340 , which also addresses ranking model pipelines, as profiling tasks will require an external support (Valerie).
So I am closing this RMP, as it already delivers value with the finished perf improvements on retrieval models.
