### ISSUE TITLE
Bring docstring coverage for Merlin repos up to 70%+

### ISSUE THREAD

**Issue by karlhigley** [NVIDIA-Merlin/Merlin#263]
# Docstring coverage:

- [ ] https://github.com/NVIDIA-Merlin/NVTabular/issues/1469
- [ ] https://github.com/NVIDIA-Merlin/models/issues/292
  - [ ] https://github.com/NVIDIA-Merlin/models/pull/297
- [x] https://github.com/NVIDIA-Merlin/systems/issues/46
- [ ] https://github.com/NVIDIA-Merlin/core/issues/48

# Core:

- [x] https://github.com/NVIDIA-Merlin/core/pull/34
- [ ] Improve docstring coverage
    https://github.com/NVIDIA-Merlin/core/pull/35
    https://github.com/NVIDIA-Merlin/core/issues/38
    https://github.com/NVIDIA-Merlin/core/issues/39
    https://github.com/NVIDIA-Merlin/core/issues/40

# Models:

- [x] NVIDIA-Merlin/Merlin#144

# NVTabular:

- [x] NVIDIA-Merlin/Merlin#144

# Systems:

- [x] NVIDIA-Merlin/Merlin#144

**Comment by viswa-nvidia** [comment]
@karlhigley , could you please check the boxes that are done and move the rest to a separate ticket.
