### ISSUE TITLE
[RMP] Finalize YouTubeDNN retrieval

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Merlin#418]
## Problem:
Most of the work for full support of YouTubeDNN is done, but there are still some pending tasks.

## Goal:
- Finish the YouTubeDNN retreival model in order to
  - Start support sequential interactions in Merlin Models, as expected by many our customers, as a first step towards upcomming support for more advanced sequential and session-based recommendation. 
  - Enable us to provide a more comprehensive benchmark of retrieval models, i.e. comparing YouTubeDNN with MF and Two-Tower.

## Constraints:
- The current YouTubeDNN uses a popularity-based sampler for sampled softmax, that assumes that the item id was categorified so that the ids are sorted by frequency decreasingly (like done by default by NVTabular `Categorify()` op)

## Starting Point:
- [ ] https://github.com/NVIDIA-Merlin/models/issues/496
- [ ] https://github.com/NVIDIA-Merlin/models/pull/473
- [ ] https://github.com/NVIDIA-Merlin/models/pull/454

**Comment by viswa-nvidia** [comment]
The problem statement doesnt' articulate what customer value is being provided

**Comment by gabrielspmoreira** [comment]
@viswa-nvidia I have refined the problem description a bit to highlight the value of the YouTubeDNN support

**Comment by viswa-nvidia** [comment]
The planned tasks don't seem to cover the problem statement. @EvenOldridge , please review

**Comment by viswa-nvidia** [comment]
@marcromeyn , what is this task blocked on ?
