### ISSUE TITLE
[RMP] Enable users to pass embedding tables directly into the input block in order to more easily support new functionality (non-trainable embeddings, different dimensions, model parallel, etc)

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Merlin#479]
## Problem:
Customers want to be able to create embeddings that support a wide variety of options. The InputBlock handles the selection of these features through arguments, however we're up to 18 arguments and it's only going to get worse.
By separating input block definition from embedding creation we can allow for a much more flexible set of embeddings support with a simpler API.
The RMP NVIDIA-Merlin/Merlin#404 introduced the `InputBlockV2` and also the `Embeddings` function that allow the user to provide a custom block for embeddings or infer the embeddings tables and their cardinality from the schema, exposing new options like setting trainable=False for embeddings.
But those new blocks are still experimental, for not being used yet by Merlin Models high-level API and have much less tests than the previous `InputBlock`

## Goal:
- [x] NVIDIA-Merlin/models#627
- [x] https://github.com/NVIDIA-Merlin/models/issues/613 - Update DLRM to use the new `EmbeddingTable` and `InputBlockV2`
- [ ] https://github.com/NVIDIA-Merlin/models/issues/604 - Update high-level API of ranking models - `DCNModel`, `DeepFMModel` - to use `InputBlockV2` and to expose the `embeddings` block to the users.
- [ ] https://github.com/NVIDIA-Merlin/models/issues/605 - Extend existing tests for `InputBlockV2`, by creating copies of existing tests for `InputBlock`, to ensure it is well tested - Moved this ticket to ENG-CI and closing the RMP ticket

## Starting Point:
- The RMP NVIDIA-Merlin/Merlin#404 is the starting point for introducing the `InputBlockV2` and also the `Embeddings` function. The PR https://github.com/NVIDIA-Merlin/models/pull/600 introduced some fixes to `InputBlockV2`

Note:
non-trainable embeddings is the pre-trained embeddings

**Comment by viswa-nvidia** [comment]
Note comment for https://github.com/NVIDIA-Merlin/models/issues/605
