### ISSUE TITLE
[RMP] Merlin Models PyTorch API

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#534]
Note: This ticket needs to capture the models related work also. 

## Problem:
Adding PyT api to Merlin models

## Starting Point:
[[RMP] Provide serving support for PyTorch models](https://github.com/NVIDIA-Merlin/Merlin/issues/255)

- [ ] Enable Distributed Data Parallel training
  - [ ] Next item prediction
  - [ ] Binary classification

- [ ] Example of how to migrate between Transformers4Rec to Merlin Models

**Comment by viswa-nvidia** [comment]
@marcromeyn please define the ticket

**Comment by EvenOldridge** [comment]
Duplicate of #893
