### ISSUE TITLE
[RMP] T4R - Support to multi-GPU training for binary classification and regression tasks

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Merlin#708]
## Problem:
Transformers4Rec supports multi-GPU training for the next-item prediction task because it uses the HF Trainer ([RMP #522](https://github.com/NVIDIA-Merlin/Merlin/issues/522)), which under-the-hood supports DataParallel / DistributedDataParallel.
The binary classification / regression tasks are currently not supported by HF Trainer, but rather trained with a custom `model.fit()` method we provided, that doesn't support DataParallel / DistributedDataParallel.

## Goal:
- Change the implementation of binary classification / regression tasks so that they can be trained (with multi-GPU) by using HF Trainer.

## Starting Point:
- [x] https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/505
- Note 505 tracks the dev in 487 and 423 
- [x] https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/487
- [ ] Binary classification - https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/423 - This a customer issue that will be solved by above issues

**Comment by viswa-nvidia** [comment]
@rnyak needs to confirm with @sararb  and confirm milestone

**Comment by rnyak** [comment]
We created a [multi-gpu example](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb) in TF4Rec for next-item prediction task. For binary-classification task we shared example PoC with the customer, and I will add code snippet into the docs in TF4Rec repo.
