### ISSUE TITLE
[RMP] Multi-Task Learning with Merlin Models

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Merlin#785]
## Problem:

Multi-Task Learning (MTL) is a popular approach to improve models accuracy, robustness and compression by training them to predict multiple outputs.  
In the field of RecSys, MTL has been widely used in **ranking models**, where multiple binary targets (e.g. the likelihood of a click, like, share, purchase) are predicted for user-item pairs. It has been also popular to train r**etrieval models**, like in [OTTO – Multi-Objective Recommender System](https://www.kaggle.com/competitions/otto-recommender-system/overview/description) Kaggle competition, where the task is to predict clicks, cart additions, and orders. 

## Goal:

The goal of this RMP is to provide to our users easy building blocks in Merlin Models for building Multi-Task Learning models.

## Constraints:

- The model tasks should be inferred automatically from the schema, where columns can be tagged as `"target"`, `"regression"` and `"classification"` (`"binary"` and `"multi_class"`).
- The user should be able to define manually the tasks by creating a single or multiple tasks per target column, with or without a task-specific tower
- It should be possible to set the `loss_weights`, so that the tasks weights can be balanced in the final `loss`
- It should be possible to set `metrics` and `weighted_metrics` per task
- It should be possible to set `sample_weight` per task
- We should provide as building blocks some architectures especially designed for multi-task learning from state-of-the-art: [MMOE](https://dl.acm.org/doi/pdf/10.1145/3219819.3220007), [PLE](https://dl.acm.org/doi/10.1145/3383313.3412236)

## Starting Point:

The early releases of Merlin Models already contained some building blocks for MTL, like 
- `parse_prediction_tasks()` which returned a `ParallelPredictionBlock` containing a number of `PredictionTask`
- A preliminary version of `MMOEBlock`
- Some logic to map tasks outputs to losses and metrics

In this RMP, we list the latest tasks / fixes / improvements to officially release the Multi-Task Learning with Merlin Models:

- [x] https://github.com/NVIDIA-Merlin/models/pull/902
- [x] https://github.com/NVIDIA-Merlin/models/pull/772
- [x] https://github.com/NVIDIA-Merlin/models/issues/914
- [x] https://github.com/NVIDIA-Merlin/models/issues/942
- [x] https://github.com/NVIDIA-Merlin/models/pull/948
