### ISSUE TITLE
[RMP] Colab for Notebooks

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Merlin#787]
## Problem:
Colab updated the environment and rapids is able to run on Colab environment. Testing and Adding Merlin notebooks to Google Colab.

## Goal:
User can explore easier Merlin when we can provide an easy integration with Colab environment.

Update:
We discussed the feasibility. Unfortunately, we cannot add automated testing of our examples in the Colab environment. It is not feasible to test all the notebooks manually for a release. 

We decided that 
- [ ] we will write a blog post, explaining how to run our examples in Colab
- [ ] reference the blog post in our examples/repo for our users

## Constraints:
We should consider only ETL and Training examples. I dont think we can provide Serving with Triton on Colab.

## Starting Point:
- [ ] POC - Testing some notebooks + adding text + explanation
- [ ] Write blog post about using Merlin on Colab environment
- [ ] Add blog post to example READMEs of our libraries: dataloader, Merlin, models, transformer4rec, NVTabular

**Comment by bschifferer** [comment]
I think we can close the ticket as we decided for a blog post
