### ISSUE TITLE
[RMP] Refactor Documentation

### ISSUE THREAD

**Issue by bschifferer** [NVIDIA-Merlin/Merlin#788]
## Problem:
Every repository has its own documentation. Users have to switch back and forth between documentations. There is not single entry point for users.

## Goal:
Provide a better user experience for our documentations

## New Functionality
- [ ] Discussion: Central Documentation (One Documentation) vs. Documentation per Repository

Additional new Pages
- [ ] Update Landing Page: Introduction
- [ ] User Guide similar to https://scikit-learn.org/stable/user_guide.html ?
- [ ] Decision Tree for finding the correct Model
- [ ] Why Merlin Page? 

## Starting Point:
- [ ] Start Document for Merlin Decision Process
- [ ] Start DRAFTs for additional Pages

**Comment by bschifferer** [comment]
I started a draft for a Merlin Decision Process:
https://docs.google.com/document/d/1FmK55tAo0wy0tHUe3eE8xqZKGDYSvy0tvq8Y036854A/edit#

**Comment by oliverholworthy** [comment]
Started a couple of things that help toward this goal of improving the docs

- Settting up the stable branch as the default branch for docs sites https://github.com/NVIDIA-Merlin/Merlin/issues/866
- Updating the theme and adding a sidebar with links to other projects in the merlin ecosystem https://github.com/NVIDIA-Merlin/Merlin/issues/866
