### ISSUE TITLE
[INF] Merlin commons - Shapes

### ISSUE THREAD

**Issue by viswa-nvidia** [NVIDIA-Merlin/Merlin#813]
- [x] Use values/offsets everywhere (and tuples nowhere)
- [x] Change dataloader output from 2-d scalars to 1-d (pulling that code from Merlin Models, Systems)
- [x] #823
- [x] Confusing list terminology (and possibly misusage of one or the other) ()-

### Tasks
- [ ] NVIDIA-Merlin/dataloader#105
- [x] NVIDIA-Merlin/Merlin#819
- [x] NVIDIA-Merlin/Merlin#820

**Comment by oliverholworthy** [comment]
I've been looking at the last point * Confusing list terminology (and possibly misusage of one or the other* from the dataloader perspective which is where most of this confusing terminology show show up.

The dataloader currently uses the dataset schema value_count (now set by the shape) to determine the output type. This has caused problems in #819 because setting the shape (value_count) changes the output type from a ragged representation (tuple of values and row_lengths) to a sparse tensor which is unsupported as an input type to the model. We can work around this by removing the shape (value_count) from the schema of the dataset when using the dataloader from Merlin Models.

The more general fix for this that is being worked toward is removing the relationship between the schema shape and the output representation of list features. And leaving that to operators to transform if required.

This would also allow us to be closer to removing the wrapper classes in Transformers4Rec and Merlin Models that work around the interface to the dataloader and change the schema with confusing terminology in the names of arguments.
