### ISSUE TITLE
[RMP] Embedding-based Retrieval Models (TF)

### ISSUE THREAD

**Issue by EvenOldridge** [NVIDIA-Merlin/Merlin#99]
We want to support classic 2-stage recommender systems.  To enable that we need retrieval models across the merlin ecosystem.  Add support for training and serving retrieval models and examples that demonstrate how to build them and connect them in a 2-stage system.  This is a precursor for 4-stage recommenders which are one of the goals of Merlin.

Depends on #102 

# Models ( Data Scientist )

### Two-tower model 
- [x]  https://github.com/NVIDIA-Merlin/models/issues/65
- [x]  https://github.com/NVIDIA-Merlin/models/pull/82
- [x]  https://github.com/NVIDIA-Merlin/models/pull/116

### Youtube DNN

- [x] https://github.com/NVIDIA-Merlin/models/pull/152

### User/Item tower model export (ideally 22.03)
In order to build an ensemble that can serve a retrieval model, we'll need both:
- [x] A model that computes a user vector from user features (i.e. the user tower)
- [x ] A set of item vectors we can load into a nearest neighbor search index (i.e. batch-predictions from the item tower)

Note: User/Item tower model export is covered by item vector export from model

### Item vector export from model
- [x]  https://github.com/NVIDIA-Merlin/models/pull/145

### Negative sampling
- https://github.com/NVIDIA-Merlin/models/issues/103
- [x] https://github.com/NVIDIA-Merlin/models/issues/113
- [x] https://github.com/NVIDIA-Merlin/models/issues/92
- [x] https://github.com/NVIDIA-Merlin/models/issues/133
- [x] https://github.com/NVIDIA-Merlin/models/issues/134
- [x] https://github.com/NVIDIA-Merlin/models/issues/135
- [x] https://github.com/NVIDIA-Merlin/models/issues/136

### Contrastive losses
- [x]  https://github.com/NVIDIA-Merlin/models/pull/166

### Evaluation Metrics (Precision/Recall/?) 
- [x] https://github.com/NVIDIA-Merlin/models/issues/170

- Needs clarity. Is there anything else ? 

# Systems (Data scientist / Product Engineer)
- [x] Triton Operators for candidate retrieval via ANN search (cuML) ( [Model Library - Serving retrieval model in Triton](https://nvaiinfa.aha.io/features/MERLIN-672) ) 
- [x] https://github.com/NVIDIA-Merlin/NVTabular/pull/1391

**Comment by viswa-nvidia** [comment]
@rnyak , could you check on User/Item tower model export. Do you ahve a ticket going for this ?

**Comment by EvenOldridge** [comment]
@marcromeyn @sararb What's the status of this:

> Item tower model forward pass as a large batch export

Do we need a ticket for this functionality?

**Comment by EvenOldridge** [comment]
@sararb @marcromeyn @rnyak @bschifferer We need to start planning out the examples for using Merlin Models in conjunction with the end to end serving POC.

**Comment by sararb** [comment]
> @marcromeyn @sararb What's the status of this:
> 
> > Item tower model forward pass as a large batch export
> 
> Do we need a ticket for this functionality?

I am not sure if I fully understand what you mean about ` Item tower model forward pass ` but this [PR]( https://github.com/NVIDIA-Merlin/models/pull/145) defined the methods to export the query/item embeddings dataset by applying query/item towers to a dataset of interactions, and it was already merged. This is a [unit test ](
https://github.com/NVIDIA-Merlin/models/blob/c0df6db16180d696400e7fab9747e907eb394cf4/tests/tf/prediction/test_batch.py#L27) related to this functionality.  

With Marc, we are also working on a draft [PR](https://github.com/NVIDIA-Merlin/models/pull/189) that converts the ItemRetrievalModel to a recommender model after training is finished. We can then apply the recommender to a batch of users and retrieve the dataset of top-k recommended items.

**Comment by karlhigley** [comment]
@sararb I think that's an artifact of a discussion we had about whether `merlin-models` or `nvtabular` would be responsible for exporting large batches of item vectors.

@EvenOldridge @viswa-nvidia I think we can drop that item, since it turns out to be a duplicate.

**Comment by karlhigley** [comment]
We've checked everything here and examples have moved to a separate epic, so this is complete.
